"""create bike

Revision ID: ed32f55ea5d5
Revises: 
Create Date: 2021-02-09 02:23:02.669003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed32f55ea5d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Location', sa.String(length=64), nullable=True),
    sa.Column('Street', sa.String(length=64), nullable=True),
    sa.Column('Distance', sa.Integer(), nullable=True),
    sa.Column('Area', sa.String(length=64), nullable=True),
    sa.Column('Status', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_bike_Area'), 'bike', ['Area'], unique=True)
    op.create_index(op.f('ix_bike_Distance'), 'bike', ['Distance'], unique=True)
    op.create_index(op.f('ix_bike_Location'), 'bike', ['Location'], unique=True)
    op.create_index(op.f('ix_bike_Status'), 'bike', ['Status'], unique=True)
    op.create_index(op.f('ix_bike_Street'), 'bike', ['Street'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bike_Street'), table_name='bike')
    op.drop_index(op.f('ix_bike_Status'), table_name='bike')
    op.drop_index(op.f('ix_bike_Location'), table_name='bike')
    op.drop_index(op.f('ix_bike_Distance'), table_name='bike')
    op.drop_index(op.f('ix_bike_Area'), table_name='bike')
    op.drop_table('bike')
    # ### end Alembic commands ###
